export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const REMOVE_REGION = 'REMOVE_REGION'

export const SELECT_STORE = 'SELECT_STORE'
export const SELECT_PRODUCTS = 'SELECT_PRODUCTS'
export const SELECT_REGIONS = 'SELECT_REGIONS'

export const DISCOUNT_UPLOAD_REQUEST = 'DISCOUNT_UPLOAD_REQUEST'
export const DISCOUNT_UPLOAD_SUCCESS = 'DISCOUNT_UPLOAD_SUCCESS'
export const DISCOUNT_UPLOAD_ERROR = 'DISCOUNT_UPLOAD_ERROR'

export const IMPORT_VIRTUAL_CARDS_REQUEST = 'IMPORT_VIRTUAL_CARDS_REQUEST'
export const IMPORT_VIRTUAL_CARDS_SUCCESS = 'IMPORT_VIRTUAL_CARDS_SUCCESS'
export const IMPORT_VIRTUAL_CARDS_ERROR = 'IMPORT_VIRTUAL_CARDS_ERROR'

export const RESET_UPLOAD_STATUS = 'RESET_UPLOAD_STATUS'
